---
- name: Download files in parallel
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  async: 600
  poll: 0
  register: download_results
  loop:
    - { url: "{{ URL_docker }}-{{ docker_version }}.tgz", dest: "{{ download_folder }}/docker-{{ docker_version }}.tgz", proc: "docker" }
    - { url: "{{ URL_compose }}/v{{ compose_version }}/{{ compose_arh }}", dest: "{{ download_folder }}/docker-compose", proc: "compose" }
    - { url: "{{ URL_harbor }}/v{{ harbor_version }}/{{ harbor_arh }}-v{{ harbor_version }}.tgz", dest: "{{ download_folder }}/{{ harbor_arh }}-v{{ harbor_version }}.tgz", proc: "harbor" }

- name: Wait for downloads to finish
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: download_status
  until: download_status.finished
  retries: 60
  delay: 10
  with_items: "{{ download_results.results }}"
