---
- name: download
  hosts: localhost
  vars_files:
  - ./vars.yml
  roles:
    - {role: download, tags: ["download,all"]}

- name: preparing
  hosts: all
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - {role: create_folder, tags: ["create_folder,all"]}
    - {role: preparing, tags: ["preparing,all"]}
#    - {role: serf, tags: ["serf,all"]}

- name: install harbor
  hosts: all
  become: true
  become_user: root
  vars_files:
    - ./vars.yml
    - ./vault.yml
  roles:
    - {role: deploy, tags: ["deploy,only_harbor,all"]}
