---
- name: download
  hosts: localhost
  vars_files:
  - ./vars.yml
  roles:
#    - {role: test, tags: ["test"]}
    - {role: download, tags: ["download"]}

- name: preparing
  hosts: all
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - {role: create_folder, tags: ["create_folder"]}
    - {role: preparing, tags: ["preparing"]}
    - {role: serf, tags: ["serf"]}

- name: install harbor
  hosts: all
  become: true
  become_user: root
  vars_files:
    - ./vars.yml
    - ./vault.yml
  roles:
    - {role: deploy, tags: ["deploy"]}
#    - {role: telegraf, tags: ["telegraf"]}
