- name: Create directories if they do not exist
  become: true
  ansible.builtin.file:
    path: "{{ item.folder }}"
    state: directory
    mode: '0755'
    owner: '0'
    group: '0'
  loop:
    - { folder: "{{ harbor_folder }}/harbor_{{ harbor_version }}" }
    - { folder: "{{ certificate_folder }}" }
